"""initial migration

Revision ID: 0bd864d868d5
Revises: 
Create Date: 2026-01-31 18:06:59.720751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bd864d868d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'prod_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('idx_product_name'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_product_name'), 'products', ['product_name'], unique=False)
    op.alter_column('products', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'prod_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
